# Generated by Django 5.0.3 on 2024-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField()),
                ("is_done", models.BooleanField(default=False)),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="todolist_service.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["is_done", "-created"],
            },
        ),
    ]
